package com.szonjabalega.cocktailrecipes.network.models

/**
 * CocktailRecipe App
 * Cocktail application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: szonja.balega@edu.bme.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param idDrink
 * @param strDrink
 * @param strDrinkAlternate
 * @param strTags
 * @param strVideo
 * @param strCategory
 * @param strIBA
 * @param strAlcoholic
 * @param strGlass
 * @param strInstructions
 * @param strInstructionsES
 * @param strInstructionsDE
 * @param strInstructionsFR
 * @param strInstructionsIT
 * @param strInstructionsZHHANS
 * @param strInstructionsZHHANT
 * @param strDrinkThumb
 * @param strIngredient1
 * @param strIngredient2
 * @param strIngredient3
 * @param strIngredient4
 * @param strIngredient5
 * @param strIngredient6
 * @param strIngredient7
 * @param strIngredient8
 * @param strIngredient9
 * @param strIngredient10
 * @param strIngredient11
 * @param strIngredient12
 * @param strIngredient13
 * @param strIngredient14
 * @param strIngredient15
 * @param strMeasure1
 * @param strMeasure2
 * @param strMeasure3
 * @param strMeasure4
 * @param strMeasure5
 * @param strMeasure6
 * @param strMeasure7
 * @param strMeasure8
 * @param strMeasure9
 * @param strMeasure10
 * @param strMeasure11
 * @param strMeasure12
 * @param strMeasure13
 * @param strMeasure14
 * @param strMeasure15
 * @param strImageSource
 * @param strImageAttribution
 * @param strCreativeCommonsConfirmed
 * @param dateModified
 */
data class Cocktail (
    val idDrink: kotlin.Long? = null,
    val strDrink: kotlin.String? = null,
    val strDrinkAlternate: kotlin.String? = null,
    val strTags: kotlin.String? = null,
    val strVideo: kotlin.String? = null,
    val strCategory: kotlin.String? = null,
    val strIBA: kotlin.String? = null,
    val strAlcoholic: kotlin.String? = null,
    val strGlass: kotlin.String? = null,
    val strInstructions: kotlin.String? = null,
    val strInstructionsES: kotlin.String? = null,
    val strInstructionsDE: kotlin.String? = null,
    val strInstructionsFR: kotlin.String? = null,
    val strInstructionsIT: kotlin.String? = null,
    val strInstructionsZHHANS: kotlin.String? = null,
    val strInstructionsZHHANT: kotlin.String? = null,
    val strDrinkThumb: kotlin.String? = null,
    val strIngredient1: kotlin.String? = null,
    val strIngredient2: kotlin.String? = null,
    val strIngredient3: kotlin.String? = null,
    val strIngredient4: kotlin.String? = null,
    val strIngredient5: kotlin.String? = null,
    val strIngredient6: kotlin.String? = null,
    val strIngredient7: kotlin.String? = null,
    val strIngredient8: kotlin.String? = null,
    val strIngredient9: kotlin.String? = null,
    val strIngredient10: kotlin.String? = null,
    val strIngredient11: kotlin.String? = null,
    val strIngredient12: kotlin.String? = null,
    val strIngredient13: kotlin.String? = null,
    val strIngredient14: kotlin.String? = null,
    val strIngredient15: kotlin.String? = null,
    val strMeasure1: kotlin.String? = null,
    val strMeasure2: kotlin.String? = null,
    val strMeasure3: kotlin.String? = null,
    val strMeasure4: kotlin.String? = null,
    val strMeasure5: kotlin.String? = null,
    val strMeasure6: kotlin.String? = null,
    val strMeasure7: kotlin.String? = null,
    val strMeasure8: kotlin.String? = null,
    val strMeasure9: kotlin.String? = null,
    val strMeasure10: kotlin.String? = null,
    val strMeasure11: kotlin.String? = null,
    val strMeasure12: kotlin.String? = null,
    val strMeasure13: kotlin.String? = null,
    val strMeasure14: kotlin.String? = null,
    val strMeasure15: kotlin.String? = null,
    val strImageSource: kotlin.String? = null,
    val strImageAttribution: kotlin.String? = null,
    val strCreativeCommonsConfirmed: kotlin.String? = null,
    val dateModified: kotlin.String? = null,
) {

}

