package com.szonjabalega.cocktailrecipes.persistence

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Cocktail(
    @PrimaryKey val idDrink: Long,
    val strDrink: String? = null,
    val strDrinkAlternate: kotlin.String? = null,
    val strTags: kotlin.String? = null,
    val strVideo: kotlin.String? = null,
    val strCategory: kotlin.String? = null,
    val strIBA: kotlin.String? = null,
    val strAlcoholic: kotlin.String? = null,
    val strGlass: kotlin.String? = null,
    val strInstructions: kotlin.String? = null,
    val strInstructionsES: kotlin.String? = null,
    val strInstructionsDE: kotlin.String? = null,
    val strInstructionsFR: kotlin.String? = null,
    val strInstructionsIT: kotlin.String? = null,
    val strInstructionsZHHANS: kotlin.String? = null,
    val strInstructionsZHHANT: kotlin.String? = null,
    val strDrinkThumb: kotlin.String? = null,
    val strIngredient1: kotlin.String? = null,
    val strIngredient2: kotlin.String? = null,
    val strIngredient3: kotlin.String? = null,
    val strIngredient4: kotlin.String? = null,
    val strIngredient5: kotlin.String? = null,
    val strIngredient6: kotlin.String? = null,
    val strIngredient7: kotlin.String? = null,
    val strIngredient8: kotlin.String? = null,
    val strIngredient9: kotlin.String? = null,
    val strIngredient10: kotlin.String? = null,
    val strIngredient11: kotlin.String? = null,
    val strIngredient12: kotlin.String? = null,
    val strIngredient13: kotlin.String? = null,
    val strIngredient14: kotlin.String? = null,
    val strIngredient15: kotlin.String? = null,
    val strMeasure1: kotlin.String? = null,
    val strMeasure2: kotlin.String? = null,
    val strMeasure3: kotlin.String? = null,
    val strMeasure4: kotlin.String? = null,
    val strMeasure5: kotlin.String? = null,
    val strMeasure6: kotlin.String? = null,
    val strMeasure7: kotlin.String? = null,
    val strMeasure8: kotlin.String? = null,
    val strMeasure9: kotlin.String? = null,
    val strMeasure10: kotlin.String? = null,
    val strMeasure11: kotlin.String? = null,
    val strMeasure12: kotlin.String? = null,
    val strMeasure13: kotlin.String? = null,
    val strMeasure14: kotlin.String? = null,
    val strMeasure15: kotlin.String? = null,
    val strImageSource: kotlin.String? = null,
    val strImageAttribution: kotlin.String? = null,
    val strCreativeCommonsConfirmed: kotlin.String? = null,
    val dateModified: kotlin.String? = null,
)